/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthRegistrationImport } from './routes/auth/registration'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as GymDayAddImport } from './routes/gym/day/add'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegistrationRoute = AuthRegistrationImport.update({
  path: '/auth/registration',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const GymDayAddRoute = GymDayAddImport.update({
  path: '/gym/day/add',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/registration': {
      preLoaderRoute: typeof AuthRegistrationImport
      parentRoute: typeof rootRoute
    }
    '/gym/day/add': {
      preLoaderRoute: typeof GymDayAddImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthLoginRoute,
  AuthRegistrationRoute,
  GymDayAddRoute,
])

/* prettier-ignore-end */
