name: CI/CD with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts

      - name: Connect and pull
        run: ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git pull"

      - name: installing packages
        run: ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && yarn"

      - name: Build the project
        run: ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && yarn build"

      - name: Start app
        run: ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && pm2 start ecosystem.config.cjs --env production"

      - name: Cleanup
        run: rm -rf ~/.ssh
